CREATE TABLE IF NOT EXISTS public.staffs
(
    id serial NOT NULL,
    "firstName" character varying(255) COLLATE pg_catalog."default",
    "lastName" character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    "phoneNumber" character varying(255) COLLATE pg_catalog."default",
    "dataOfBirth" character varying(255) COLLATE pg_catalog."default",
    "profilePix" character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    state character varying(255) COLLATE pg_catalog."default",
    lga character varying(255) COLLATE pg_catalog."default",
    "bankName" character varying(255) COLLATE pg_catalog."default",
    "accountName" character varying(255) COLLATE pg_catalog."default",
    "accountNumber" integer,
    "walletId" integer,
    "walletBalance" integer DEFAULT 0,
    "bankAccountBalance" integer DEFAULT 0,
    status character varying(255) COLLATE pg_catalog."default" DEFAULT 'Active'::character varying,
    role character varying(255) COLLATE pg_catalog."default" DEFAULT 'staff'::character varying,
    "employmentType" character varying(255) COLLATE pg_catalog."default",
    "businessId" integer,
    bonus integer DEFAULT 0,
    deduction integer DEFAULT 0,
    "totalPayable" integer DEFAULT 0,
    "paymentAccount" character varying(255) COLLATE pg_catalog."default" DEFAULT 'wallet'::character varying,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT staffs_pkey PRIMARY KEY (id)
)
