apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
        - name: business
          image: linx/business
          env:
            - name: username
              value: "postgres"
            - name: password
              value: "postgres"
            - name: database
              value: "business"
            - name: host
              value: "localhost"
            - name: dialect
              value: "postgres"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: business-srv
spec:
  selector:
    app: business
  ports:
    - name: business
      protocol: TCP
      port: 3000
      targetPort: 3000
