apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff
  template:
    metadata:
      labels:
        app: staff
    spec:
      containers:
        - name: staff
          image: linx/staff
          env:
            - name: username
              value: "postgres"
            - name: password
              value: "postgres"
            - name: database
              value: "staff"
            - name: host
              value: "localhost"
            - name: dialect
              value: "postgres"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: staff-srv
spec:
  selector:
    app: staff
  ports:
    - name: staff
      protocol: TCP
      port: 3000
      targetPort: 3000
